### ISSUE TITLE
🛠️ Handle 404 errors to avoid crashes on CLI

### ISSUE THREAD

**Issue by davidmoremad** [davidmoremad/dome9#6]
```bash
Traceback (most recent call last):
  File "C:\Users\david\Repositories\dome9-cli\cli\dome9cli.py", line 304, in <module>
    fire.Fire(Dome9CLI())
  File "C:\Users\david\.virtualenvs\dome9-cli-b-5h-f_6\lib\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "C:\Users\david\.virtualenvs\dome9-cli-b-5h-f_6\lib\site-packages\fire\core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "C:\Users\david\.virtualenvs\dome9-cli-b-5h-f_6\lib\site-packages\fire\core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "C:\Users\david\Repositories\dome9-cli\cli\dome9cli.py", line 294, in get_assessment
    data = self._dome9.get_assessment(assessmentId)
  File "C:\Users\david\.virtualenvs\dome9-cli-b-5h-f_6\lib\site-packages\dome9\dome9.py", line 426, in get_assessment
    return self._get(route='AssessmentHistoryV2/%s' % str(assessmentId))
  File "C:\Users\david\.virtualenvs\dome9-cli-b-5h-f_6\lib\site-packages\dome9\dome9.py", line 65, in _get
    return self._request('get', route, payload)
  File "C:\Users\david\.virtualenvs\dome9-cli-b-5h-f_6\lib\site-packages\dome9\dome9.py", line 61, in _request
    raise Exception(err)
Exception: {'code': 404, 'message': 'Not Found', 'content': b'Resource with id 2222222222222 of type AssessmentHistoryEntity was not found'}
```

**Comment by davidmoremad** [comment]
Better solution on CLI initialization:

```
if __name__ == '__main__':
    try:
        fire.Fire(Dome9CLI())
        sys.exit(0)
    # Ctrl-C
    except KeyboardInterrupt as e:
        raise e
    # sys.exit()
    except SystemExit as e:
        raise e
    except Exception as e:
        print(e)
        sys.exit(0)
```

**Comment by davidmoremad** [comment]
Closed on https://github.com/Telefonica/dome9-cli/commit/a84c4db0ddf07d91067f0c82d80090b489e7c266
